### ISSUE TITLE
libf77blas.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by Dacetylan** [gavinlyonsrepo/raspberrypi_tempmon#2]
pip installation: sudo apt-get install python3-pip
numpy installation: pip3 install numpy
numpy reinstallation: pip3 install numpy --no-cache-dir
operating system: raspbian strecth lite
I have both python3 and python2 installed
I did not build form source

ERROR:

`
Traceback (most recent call last):
File "/usr/local/lib/python3,5/dist-packages/numpy/core/__init__.py", line 16, in <module>
  from . import multiarray
File "/usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.py", line 12, in <module>
  from . import overrides
File "/usr/local/lib/python3.5/dist-packages/numpy/core/overrides.py", line 6, in <module>
  from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occured:

Traceback (most recent call last):
File "/usr/local/bin/rpi_tempmon.py", line 33, in <module>
  from rpiTempMod import RpiTempmonGraph
File "/usr/local/lib/python3.5/dist-packages/rpiTempMod/RpiTempmonGraph.py", line 10, in <module>
  import matplotlib as mpl
File "/usr/local/lib/python3.5/dist-packages/matplotlib/__init__.py", line 141, in <module>
  from . import cbook, rcsetup
File "/usr/local/lib/python3.5/dist-packages/matplotlib/cbook/__init__.py", line 33, in <module>
  import numpy as np
File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
  from . import core
File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 47, in <module>
  raise ImportError(msg)
ImportError:
IMMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
...
Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
`

**Comment by gavinlyonsrepo** [comment]
Hi 

I have never seen this before.

The error occurs  when _Rpi_tempmon_ tries to import _Matplotlib_ which traces back to _numpy_.
_Matplotlib_ is a dependency of _Rpi_tempmon_.
The _numpy_ package is a dependency of _Matplotlib_. 

I suspect there is an issue with the installation or setup of numpy on your machine, an old version or missing dependency, perhaps.
I have done some research on error message.
libf77blas.so.3 refers to the _blas_ package which is dependency of _numpy_
https://github.com/lhelontra/tensorflow-on-arm/issues/10
Its suggested installing Atlas
sudo apt-get install libatlas-base-dev
You could try this or you could try uninstalling or reinstalling matplotlib or numpy
or upgrading to latest version.

Can you tell me what version of 
- RPi_tempmon.py
- Matplotlib
- numpy
you have installed.
 
Regards

**Comment by gavinlyonsrepo** [comment]
Closed due to lack of response. Upstream Dependencies issue.
