### ISSUE TITLE
Issues with dependencies on RPi4

### ISSUE THREAD

**Issue by magicaljellybeans** [gavinlyonsrepo/raspberrypi_tempmon#3]
Raspberry Pi4 32 bit Buster
Python 3.7.3
pip 18.1

Tried running this this but getting a trail of missing/inaccesible dependencies.
All the following is happening when running `rpi_tempmon.py -ST`.
First one that comes up is this:
```
Traceback (most recent call last):
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/tempmon/venv/bin/rpi_tempmon.py", line 32, in <module>
    from rpiTempMod import RpiTempmonGraph
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/rpiTempMod/RpiTempmonGraph.py", line 10, in <module>
    import matplotlib as mpl
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 28, in <module>
    import numpy as np
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/home/tom/tempmon/venv/bin/python3"
  * The NumPy version is: "1.20.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

Followed the numpy link in there and it has some specific advice for pi users:
`sudo apt-get install libatlas-base-dev`

So I do that, when I try to run the script again:
```
Traceback (most recent call last):
  File "/home/tom/tempmon/venv/bin/rpi_tempmon.py", line 32, in <module>
    from rpiTempMod import RpiTempmonGraph
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/rpiTempMod/RpiTempmonGraph.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
```

So after googling I find I can fix with `sudo apt-get install libopenjp2-7`.
Try again, and a similar error comes up, fixed with `sudo apt install libtiff5`.

Next I get `ModuleNotFoundError: No module named 'tkinter'`
So I `sudo apt install python3-tk`.

Next, and as far as I've got:
```
Traceback (most recent call last):
  File "/home/tom/tempmon/venv/bin/rpi_tempmon.py", line 32, in <module>
    from rpiTempMod import RpiTempmonGraph
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/rpiTempMod/RpiTempmonGraph.py", line 12, in <module>
    import matplotlib.pyplot as plt
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "/home/tom/tempmon/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 287, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
```

Any idea why all this might be happening?

**Comment by gavinlyonsrepo** [comment]
Hi 

Sorry for delay , Have you resolved your problem?

All of these errors I assume are related to the installation and setup of dependency "matplotlib" and its libraries and dependency(numpy etc). I have not worked on this project in a while.

I don't have  a RPI-4 so I a cannot verify or replicate  if problems are related to the pi4 or  "Raspian buster"
I am running a RPI-3 , Raspbian Sketch 9.13  with Python 3.5.3.
Everything is running fine here. 

There is some sort of difference between your installation and environment  and mine , in theory 
matplotlib should be installed by setup.py on installation  of rpi_tempmon.py if it was missing.. 

Can you tell me where/how matplotlib is installed  and which version?
In terminal type following commands and send me output

`
dpkg -l | grep "matplotlib"

& 

pip3 list | grep "matplotlib"

`
I am using matpltlib 3.0.3 installed by pip, I suspect you are using an older version of matplotlib installed by apt 
install matplotlib by pip if that is case and see what happens. 

Regards

**Comment by gavinlyonsrepo** [comment]
Issue is matplotlib is not installed by pip most likely , will update readme with note . closed.
